### PR TITLE
Update Mshr

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
```
Encountered problems while solving:
[675](https://github.com/pyiron/docker-stacks/actions/runs/4081042339/jobs/7034085060#step:7:676)
  - package lammps-2022.06.23-py39h18ede88_mpich_3 requires mpich >=4.0.2,<5.0a0, but none of the providers can be installed
```

**Comment by jan-janssen** [comment]
Seems like the DAMASK executable is no longer compatible to the pyiron wrapper or something broke:
```
[NbConvertApp] Converting notebook /home/jovyan/damask_tutorial.ipynb to notebook
[5](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:6)
[IPKernelApp] ERROR | Error in message handler
[6](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:7)
Traceback (most recent call last):
[7](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:8)
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 461, in dispatch_queue
[8](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:9)
    await self.process_one()
[9](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:10)
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 450, in process_one
[10](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:11)
    await dispatch(*args)
[11](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:12)
TypeError: object NoneType can't be used in 'await' expression
[12](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:13)
Traceback (most recent call last):
[13](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:14)
  File "/opt/conda/bin/jupyter-nbconvert", line 11, in <module>
[14](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:15)
    sys.exit(main())
[15](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:16)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
[16](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:17)
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
[17](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:18)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 1043, in launch_instance
[18](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:19)
    app.start()
[19](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:20)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 361, in start
[20](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:21)
    self.convert_notebooks()
[21](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:22)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 533, in convert_notebooks
[22](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:23)
    self.convert_single_notebook(notebook_filename)
[23](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:24)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 498, in convert_single_notebook
[24](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:25)
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
[25](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:26)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 427, in export_single_notebook
[26](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:27)
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
[27](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:28)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
[28](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:29)
    return self.from_file(f, resources=resources, **kw)
[29](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:30)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 208, in from_file
[30](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:31)
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
[31](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:32)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
[32](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:33)
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
[33](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:34)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 147, in from_notebook_node
[34](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:35)
    nb_copy, resources = self._preprocess(nb_copy, resources)
[35](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:36)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 334, in _preprocess
[36](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:37)
    nbc, resc = preprocessor(nbc, resc)
[37](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:38)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
[38](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:39)
    return self.preprocess(nb, resources)
[39](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:40)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 84, in preprocess
[40](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:41)
    self.preprocess_cell(cell, resources, index)
[41](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:42)
  File "/opt/conda/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 105, in preprocess_cell
[42](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:43)
    cell = self.execute_cell(cell, index, store_history=True)
[43](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:44)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
[44](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:45)
    return just_run(coro(*args, **kwargs))
[45](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:46)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
[46](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:47)
    return loop.run_until_complete(coro)
[47](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:48)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
[48](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:49)
    return future.result()
[49](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:50)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
[50](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:51)
    self._check_raise_for_error(cell, exec_reply)
[51](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:52)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
[52](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:53)
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
[53](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:54)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
[54](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:55)
------------------
[55](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:56)
job.run()
[56](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:57)
------------------
[57](https://github.com/pyiron/docker-stacks/actions/runs/4081411430/jobs/7034768771#step:16:58)
```
This might be related to https://github.com/pyiron/pyiron-resources/pull/55

**Comment by jan-janssen** [comment]
@mbruns91 Do you need the latest version of DAMASK? Alternatively this is now a good option for you to learn more about the build process. As the Docker container builds successfully but then fails at the stage of executing the notebooks, the next steps are: 
- Download the repository
- Build the docker container for `pyiron/base`
- Build the docker container for `pyiron/continuum`
- Start an instance of the `pyiron/continuum` docker container 
- Modify the DAMASK run scripts in `/opt/conda/share/pyiron/damask/bin` as discussed in https://github.com/pyiron/pyiron-resources/pull/55
- Try to execute the notebook `damask_tutorial.ipynb` inside the docker container

Once this works, then we can merge https://github.com/pyiron/pyiron-resources/pull/55 release a new version of the `pyiron-data` conda package and rebuild the docker container with this new version. Is this something you can take a look at ?

**Comment by mbruns91** [comment]
It doesn't necessarily need to be the most recent version of `Damask`, the latest version compatible with `pyiron_continuum` is totally fine. Most importantly, it needs to work.

**Comment by jan-janssen** [comment]
> Most importantly, it needs to work.

The release from yesterday `2023-02-03` should work just fine:
https://hub.docker.com/r/pyiron/continuum/tags
This is more just some additional clean up as I was able to solve two bugs with the `mshr` package on conda-forge yesterday https://github.com/conda-forge/mshr-feedstock/pull/27 and https://github.com/conda-forge/mshr-feedstock/pull/31 . So updating these packages as part of this current pull request will also allow us to use the latest version of DAMASK.

**Comment by jan-janssen** [comment]
I started an mybinder environment for the testing https://mybinder.org/v2/gh/jan-janssen/test-damask/HEAD it is based on the GitHub repository https://github.com/jan-janssen/test-damask

**Comment by jan-janssen** [comment]
This can be merged on the 4th of February 2023 to release a new version, as I already released a version for the 3rd of February.

**Pull request merged**
