### PR TITLE
Mpi fix

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
@liamhuber I am able to reproduce your issue with the following repository https://github.com/jan-janssen/pyiron-md

**Comment by muh-hassani** [comment]
@jan-janssen I will test whether these environmental variables resolve the issue.

**Comment by muh-hassani** [comment]
The environmental variable solved the issue.

**Comment by liamhuber** [comment]
Thanks @jan-janssen and @muh-hassani!!!

**Comment by jan-janssen** [comment]
I can confirm also my test repository works now fine, so we should be all set. Thanks @liamhuber for testing and identify this issue.

**Pull request merged**
