### PR TITLE
Update to ubuntu 22.04

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
The image contains `python=3.10.8` so just updating the image does not work.

**Comment by jan-janssen** [comment]
This seems to be incompatible with the old version of LAMMPS: 
```
Encountered problems while solving:
[648](https://github.com/pyiron/docker-stacks/actions/runs/4079054369/jobs/7030007421#step:7:649)
  - package lammps-2021.07.30-py39h3296099_mpich_3 requires python >=3.9,<3.10.0a0, but none of the providers can be installed
[649](https://github.com/pyiron/docker-stacks/actions/runs/4079054369/jobs/7030007421#step:7:650)
  - package mp-api-0.30.5-pyhd8ed1ab_2 requires pymatgen >=2022.3.7, but none of the providers can be installed
```

**Comment by mbruns91** [comment]
That's exactly the problem I faced earlier today. Using a more recent version of LAMMPS creates another problem when building the continuum image, related issue #103 , I guess. My first guess was to use amore recent base image but stick to ubuntu 20.04 nevertheless. But unfortunately there, also python 3.10 is default.

**Comment by mbruns91** [comment]
Also, just forcing `python =3.9` in `continuum/environment.yml` completely breaks this image... which is reasonable when I think about it. Is it really neccessary to install both `LAMMPS` and `fenics` in `continuum`?

**Comment by jan-janssen** [comment]
> Is it really neccessary to install both `LAMMPS` and `fenics` in `continuum`?

The old `damask` example calculates concentration dependent elastic constants with `LAMMPS` and then uses the output in `damask`. And `fenics` is an alternative continuum package, so yes from my perspective both are required.

**Comment by jan-janssen** [comment]
To explain this limitation, the old version of `fenics` which seems to be the only working one, requires an old version of `hdf5` and only an old version of `lammps` is compiled with the old version of `hdf5` which restricts us to python 3.9.

**Pull request closed without merging**
