### PR TITLE
Try fixing the permissions 

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
@muh-hassani Can you try fix these changes also work for you locally? From my perspective they make the docker files much more clear.

**Comment by muh-hassani** [comment]
These changes were basically merged to the fenics_image branch. Am I right? 
Yes, indeed. It also avoids some unnecessary repetition. Thanks Jan.

**Comment by jan-janssen** [comment]
Yes, but it applies to all container images that is why we should test it, before merging this one.

**Comment by muh-hassani** [comment]
I see. I will try them locally. The changes in these lines can affect the permission of the users. I will test it now.

**Comment by muh-hassani** [comment]
So far, my test on pyiron/base was successful.  I will test pyiron/md for reassurance.

**Comment by muh-hassani** [comment]
pyiron/md also did not have any permission issue. I guess it is ready to be merged.

**Pull request merged**
