### PR TITLE
Update July 2021

### PR DESCRIPTION
**Pull request by muh-hassani**
- updating the Base image to jupyter/base-notebook:ubuntu-20.04
    The old taging was confusing at least for me with a large number; therefore I prefer to have a meaningful tag name.  I checked the size of image and it is even smaller using this named tag. To update the name_tag, we can update the hash digest via `@sha256:digest_number`
- using mamba to make the build process faster
- update the dependencies
- updated the readme

### CODE REVIEW

**Comment by muh-hassani** [comment]
@jan-janssen, I would like to merge this after the new pyiron_continuum being released and updating the continuum image.

**Comment by jan-janssen** [comment]
I created an openmpi version for DAMASK https://github.com/conda-forge/damask-feedstock/pull/35

**Comment by muh-hassani** [comment]
> 
> 
> I created an openmpi version for DAMASK [conda-forge/damask-feedstock#35](https://github.com/conda-forge/damask-feedstock/pull/35)

Thanks @jan-janssen. I will update the environment accordingly.

**Comment by muh-hassani** [comment]
I will merge this to update our docker images, but there are open issues, which I need to take care of soon.

**Pull request merged**
