### PR TITLE
minimal updates 

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
Only the experimental tests fail: 
```
---------------------------------------------------------------------------
56
AttributeError                            Traceback (most recent call last)
57
/tmp/ipykernel_83/193066868.py in <module>
58
----> 1 job = pr.create_job(job_type=pr.job_type.MatchSeries, job_name="toy")
59

60
/opt/conda/lib/python3.9/site-packages/pyiron_base/project/generic.py in create_job(self, job_type, job_name, delete_existing_job)
61
    297         """
62
    298         job_name = job_name.replace(".", "_")
63
--> 299         job = JobType(
64
    300             job_type,
65
    301             project=ProjectHDFio(project=self.copy(), file_name=job_name),
66

67
/opt/conda/lib/python3.9/site-packages/pyiron_base/job/jobtype.py in __new__(cls, class_name, project, job_name, job_class_dict, delete_existing_job)
68
     61         else:
69
     62             raise TypeError()
70
---> 63         job = job_class(project, job_name)
71
     64         if job.job_id is not None and not os.path.exists(job.project_hdf5.file_name):
72
     65             job.logger.warning(
73

74
~/pyiron_experimental/matchseries.py in __init__(self, project, job_name)
75
      7     def __init__(self, project, job_name):
76
      8         super().__init__(project, job_name)
77
----> 9         self.input = MatchSeriesInput()
78
     10         self.executable = "matchSeries 2> output.log"
79
     11 
80

81
AttributeError: can't set attribute
82
AttributeError: can't set attribute
```

**Comment by jan-janssen** [comment]
The issue is the same as in https://github.com/pyiron/pyiron_experimental/pull/54 so we have to fix `pyiron_experimental` first.

**Comment by jan-janssen** [comment]
The required changes are included in `0.0.2` - https://github.com/conda-forge/pyiron_experimental-feedstock/pull/4 - so the build should work fine in approximately one hour - once the conda package is available.

**Comment by muh-hassani** [comment]
@jan-janssen thanks for fixing the issue. So I will close https://github.com/pyiron/docker-stacks/pull/94

**Pull request merged**
